/**
 * A collection of data processing jobs that form a directed acyclic graph
 */
 export interface Pipeline {
    /**
     * The unique identifier for a pipeline
     */
    id: string
    /**
     * Useful information for a catalog
     */
    metadata: {
      /**
       * Name of the pipeline
       */
      name?: string
      /**
       * Description of the pipeline
       */
      description?: string
      /**
       * Description of the pipeline as generated by code
       */
      autodescription?: string
      /**
       * User who created the pipeline
       */
      creator?: string
      /**
       * Date and time the pipeline was created
       */
      created?: string
      /**
       * Date and time the task was last updated
       */
      modified?: string
      /**
       * Date and time the pipeline was last run
       */
      lastrun?: string
      /**
       * Whether this pipeline should appear in the catalog
       */
      publish?: boolean
      [k: string]: unknown
    }
    /**
     * Data transformations that must run as part of this pipeline
     */
    pipelineids?:string[]
    taskCopies?:Task[]
    tasks:string[]
    [k: string]: unknown
  }
  