/**
 * A data processing job
 */
 export interface Task {
    /**
     * The unique identifier for a task
     */
    taskid: string
    /**
     * IDs of all pipelines that contain this task
     */
    pipelineids?: string[]
    /**
     * The type of task (e.g. 'table, recipe, AWS RDS ingest, aggregate, join, etc.')
     */
    type?: string
    /**
     * The source data for the task
     */
    source: {
      /**
       * The type of data source (internal means IRIS)
       */
      type: string
      /**
       * The tasks that this task depends upon, identified by their unique identifier
       */
      tasks?: string[]
      [k: string]: unknown
    }
    /**
     * Description of the computation this task will do
     */
    compute?: {
      /**
       * The operation to perform
       */
      operation?: string
      /**
       * Signals this computation uses a structured format which is good for UIs
       */
      template?: {
        [k: string]: unknown
      }
      [k: string]: unknown
    }
    /**
     * The output data set for the task
     */
    sink: {
      /**
       * The type of data sink (internal means IRIS)
       */
      type: string
      /**
       * The (view or table) name of the data sink
       */
      name: string
      /**
       * Field names of the data sink
       */
      properties?: string[]
      /**
       * The namespace of the data sink
       */
      namespace?: string
      [k: string]: unknown
    }
    /**
     * Useful information for a catalog
     */
    metadata: {
      /**
       * Name of the task
       */
      name?: string
      /**
       * Description of the task
       */
      description?: string
      /**
       * Description of the task as generated by code
       */
      autodescription?: string
      /**
       * User who created the task
       */
      creator?: string
      /**
       * Date and time the task was created
       */
      created?: string
      /**
       * Date and time the task was last updated
       */
      modified?: string
      /**
       * Date and time the task was last run
       */
      lastrun?: string
      /**
       * Whether this task should appear in the catalog
       */
      publish?: boolean
      required?: ["name", "creator", "created"]
      lasterror?: string
      [k: string]: unknown
    },
    x?:number,
    y?:number,
    [k: string]: unknown
  }
  